HAI 1.2
   OBTW
      Lolhello by Antzei Zjusttilol, (c) 2019 LOL ALLZ RIGHZ REZERVD
   TLDR
   CAN HAS STDIO?
   I HAS A HELOU ITZ "HAI"
   I HAS A YRNAMEZ ITZ ""
   VISIBLE "HAI YO!!!1!!"
   VISIBLE "WHO ITZ U LOL?!:)"
   VISIBLE "> "!
   GIMMEH YRNAMEZ
   BOTH SAEM YRNAMEZ AN "", O RLY?
      YA RLY
         VISIBLE "GTFOH LOL ANONZ IDIOZ"
      NO WAI
         VISIBLE HELOU " " YRNAMEZ " U LOL BSTRD!!!1!"
   OIC
   VISIBLE "CU LOLZ"
KTHXBYE
